### ISSUE TITLE
Cannot read property of _value of undefined

### ISSUE THREAD

**Issue by Return-1** [DrewML/webpack-emit-all-plugin#2]
When adding the plugin to webpack and running it i get the following:

`Cannot read property '_value' of undefined`

This happens in line 22 of the plugin
`const source = mod._source._value;`

**Comment by DrewML** [comment]
Can you provide a minimal example project I can use to replicate the issue?

**Comment by AylaJK** [comment]
In testing with my own project, I would get this error if a module was [external](https://webpack.js.org/configuration/externals/). This specific case was able to be fixed by adding a test such as `if (mod.external) return;`. Not sure what other configurations can cause this error.

**Comment by DrewML** [comment]
Good catch @AylaJK. We probably just need to ignore externals similar to [how `MultiModule` types are ignored](https://github.com/DrewML/webpack-emit-all-plugin/blob/58bb93e4e72f9b646b877d6c46a1679f3f76e92d/index.js#L23)

**Comment by FL0RIANMEYER** [comment]
#4

**Comment by DrewML** [comment]
Fixed by @FL0RIANMEYER and release pushed. Thanks!
